import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/layouts/Navbar";
import Footer from "@/Components/layouts/Footer";
import localFont from 'next/font/local'

const poppins = Poppins({
  weight: ['200', '300', '400', '500', '600', '700']
})

export const banglaFont = localFont({
  src: './../fonts/mayaboti-normal.ttf'
})

export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
